<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.braintribe.gm</groupId>
        <artifactId>parent</artifactId>
        <version>[2.0,2.1)</version>
    </parent>
    <artifactId>reasoned-value-descriptor-processing</artifactId>
    <version>2.0.2</version>
    <dependencies>
        <dependency>
            <groupId>com.braintribe.gm</groupId>
            <artifactId>gm-core</artifactId>
            <version>${V.com.braintribe.gm}</version>
        </dependency>
        <dependency>
            <groupId>com.braintribe.gm</groupId>
            <artifactId>essential-reason-model</artifactId>
            <version>${V.com.braintribe.gm}</version>
            <?tag asset ?>
        </dependency>
        <dependency>
            <groupId>com.braintribe.gm</groupId>
            <artifactId>value-descriptor-model</artifactId>
            <version>${V.com.braintribe.gm}</version>
            <?tag asset ?>
        </dependency>
    </dependencies>
    <properties>
        <archetype>library</archetype>
    </properties>
</project>
