package com.braintribe.gm.config.yaml.index;

import static com.braintribe.utils.lcd.CollectionTools2.newList;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

import com.braintribe.logging.Logger;
import com.braintribe.utils.lcd.Lazy;

/**
 * @author peter.gazdik
 */
public class ClasspathIndex {

	/**
	 * File containing root dirs and files of an artifact meant to be treated as resources.
	 * <p>
	 * Only relevant when debugging while a given artifact with resources is not on the classpath as a jar, but with its compilation output folder.
	 * 
	 * @see #RESOURCES_INDEX_FILE_NAME
	 */
	private static final String RESOURCES_DECLARATION_FILE_NAME = "META-INF/classpath-resources.txt";

	// URL EXAMPLE - Project in IDE on classpath:
	// toString: file:/C:/git-dir/res-in-ws/classes/META-INF/classpath-index.txt
	// getPath : /C:/git-dir/res-in-ws/classes/META-INF/classpath-index.txt
	//
	// URL EXAMPLE - JAR on classpath:
	// toString: jar:file:/C:/maven-repo/res-on-cp/1.0/res-on-cp-1.0.jar!/META-INF/classpath-index.txt
	// getPath : file:/C:/maven-repo/res-on-cp/1.0/res-on-cp-1.0.jar!/META-INF/classpath-index.txt
	/** File listing all the files within declared {@link #RESOURCES_DECLARATION_FILE_NAME}, generated when building an artifact. */
	private static final String RESOURCES_INDEX_FILE_NAME = "META-INF/classpath-index.txt";

	/**
	 * Names the artifact a resource belongs to, as {@code artifactId=<id>}. Read from the slots of an assembled filesystem mirror produced before the
	 * central {@link #FILESYSTEM_INDEX_FILE_NAME}. It is optional; without it the slot folder name is used.
	 */
	private static final String LEGACY_MIRROR_ARTIFACT_ID_FILE_NAME = "META-INF/classpath-origin.properties";

	/**
	 * Generated by the build next to the classes and resources of an artifact. Its {@code groupId} and {@code artifactId} identify the artifact of the
	 * resources. An artifact built before the descriptor was packaged has none, and then the artifactId is derived from the jar name or the project
	 * folder, while the groupId stays unknown.
	 */
	private static final String ARTIFACT_DESCRIPTOR_FILE_NAME = "META-INF/artifact-descriptor.properties";

	/**
	 * Index for resources extracted from artifacts that contain resources and nothing else, consisting of all the entries from the corresponding
	 * {@link #RESOURCES_INDEX_FILE_NAME} files.
	 * <p>
	 * It lies at the root of the mirror, next to one folder per artifact, and is a UTF-8 properties file:
	 *
	 * <pre>
	 * formatVersion=1
	 * artifact.count=2
	 * artifact.0.folder=address-book-configuration-1.0
	 * artifact.0.groupId=example.address-book
	 * artifact.0.artifactId=address-book-configuration
	 * artifact.0.sourceName=address-book-configuration-1.0.jar
	 * artifact.0.resource.count=2
	 * artifact.0.resource.0.path=ADDRESS-BOOK-CONF/address-book.yaml
	 * artifact.0.resource.1.path=static/logo.svg
	 * artifact.1.folder....
	 * </pre>
	 *
	 * Every key but {@code groupId} and {@code sourceName} is mandatory. A folder or a path that leaves its parent, or that names something missing, is rejected. Values
	 * escape backslash, newline and {@code =}.
	 * <p>
	 * Blocks are written in {@code folder} order, so the same input always gives the same file.
	 */
	private static final String FILESYSTEM_INDEX_FILE_NAME = "index.properties";

	private static final Logger log = Logger.getLogger(ClasspathIndex.class);

	private final ClassLoader classLoader;
	private final List<FilesystemSource> filesystemSources;

	private final Lazy<List<ClasspathEntry>> lazyIndex = new Lazy<List<ClasspathEntry>>(this::loadIndex);

	public ClasspathIndex() {
		this(ClasspathIndex.class.getClassLoader(), Collections.emptyList());
	}

	public ClasspathIndex(ClassLoader classLoader) {
		this(classLoader, Collections.emptyList());
	}

	/** Creates an index backed exclusively by an assembled filesystem mirror. */
	public ClasspathIndex(Path filesystemRoot) {
		this(List.of(filesystemSource(filesystemRoot, "")));
	}

	/**
	 * Creates an index backed exclusively by one or more artifact-scoped filesystem mirrors.
	 * <p>
	 * A source's logical prefix is prepended to every indexed or directly discovered path. This permits a physically clearer projection such as
	 * {@code effective-conf/<artifact>/foo.yaml} to retain its canonical classpath identity {@code HICONIC-CONF/foo.yaml}. Later sources replace an
	 * entry with the same logical path and artifact, allowing effective projections to coexist with a complete packaged-resource mirror. An unknown
	 * groupId counts as the same artifact as a known one.
	 */
	public ClasspathIndex(List<FilesystemSource> filesystemSources) {
		this(null, requireFilesystemSources(filesystemSources));
	}

	public static FilesystemSource filesystemSource(Path root, String logicalPrefix) {
		return filesystemSource(root, logicalPrefix, List.of());
	}

	/**
	 * Creates an indexed filesystem source while excluding selected physical resource prefixes. This is useful when a packaged resource mirror
	 * remains authoritative for general resources, but a compiled configuration space replaces its raw {@code HICONIC-CONF/} contributions.
	 */
	public static FilesystemSource filesystemSource(Path root, String logicalPrefix, Collection<String> excludedResourcePrefixes) {
		return new FilesystemSource(requireFilesystemRoot(root), normalizeLogicalPrefix(logicalPrefix),
				normalizeResourcePrefixes(excludedResourcePrefixes), Set.of(), true, false, null, List.of());
	}

	/**
	 * Creates a direct slot source. Every direct child directory is a slot and every regular file below it is exposed without requiring
	 * classpath-style {@code META-INF} indexes.
	 */
	public static FilesystemSource filesystemSlots(Path root, String logicalPrefix) {
		return new FilesystemSource(requireFilesystemRoot(root), normalizeLogicalPrefix(logicalPrefix), Set.of(), Set.of(), false, false, null,
				List.of());
	}

	/** Exposes one ordinary directory tree as one logical artifact, without generated indexes or slot folders. */
	public static FilesystemSource filesystemTree(Path root, String logicalPrefix, String artifactId) {
		return filesystemTree(root, logicalPrefix, artifactId, List.of());
	}

	/** Exposes one ordinary directory tree while omitting physical files which are exposed through explicit mappings. */
	public static FilesystemSource filesystemTree(Path root, String logicalPrefix, String artifactId,
			Collection<String> excludedRelativePaths) {
		if (artifactId == null || artifactId.isBlank())
			throw new IllegalArgumentException("artifactId must not be empty");
		return new FilesystemSource(requireFilesystemRoot(root), normalizeLogicalPrefix(logicalPrefix), Set.of(),
				normalizeResourcePaths(excludedRelativePaths), false, true, artifactId, List.of());
	}

	/**
	 * Exposes materialized files under their original logical paths and artifact identities. The physical path may differ after collision handling.
	 */
	public static FilesystemSource filesystemMappings(Path root, Collection<FilesystemMapping> mappings) {
		if (mappings == null)
			throw new NullPointerException("mappings must not be null");
		return new FilesystemSource(requireFilesystemRoot(root), "", Set.of(), Set.of(), false, false, null, List.copyOf(mappings));
	}

	/**
	 * A materialized file and the artifact it came from. The groupId is empty if it is not known, the artifactId is a plain artifactId, never a
	 * {@code groupId:artifactId} coordinate.
	 */
	public record FilesystemMapping(String logicalPath, String materializedPath, String groupId, String artifactId) {
		public FilesystemMapping {
			logicalPath = canonicalResourcePath(requireMappingValue(logicalPath, "logicalPath"));
			materializedPath = canonicalResourcePath(requireMappingValue(materializedPath, "materializedPath"));
			if (groupId == null)
				throw new NullPointerException("groupId must not be null, use an empty string if it is not known");
			if (artifactId == null || artifactId.isBlank())
				throw new IllegalArgumentException("artifactId must not be empty");
			if (artifactId.indexOf(':') >= 0)
				throw new IllegalArgumentException("artifactId must not be a coordinate, pass the groupId separately: " + artifactId);
		}
	}

	private ClasspathIndex(ClassLoader classLoader, List<FilesystemSource> filesystemSources) {
		this.classLoader = classLoader;
		this.filesystemSources = filesystemSources;
	}

	public List<ClasspathEntry> all() {
		return Collections.unmodifiableList(lazyIndex.get());
	}

	public List<ClasspathEntry> forPrefix(String prefix) {
		List<ClasspathEntry> all = lazyIndex.get();

		int l = findBoundary(all, prefix, true);
		if (l == -1)
			return Collections.emptyList();

		int h = findBoundary(all, prefix, false);

		return Collections.unmodifiableList(all.subList(l, h + 1));
	}

	private int findBoundary(List<ClasspathEntry> all, String prefix, boolean low) {
		int l = 0;
		int h = all.size() - 1;

		int resultCandidate = -1;

		while (l <= h) {
			int m = (l + h) / 2;
			ClasspathEntry e = all.get(m);

			if (e.path.startsWith(prefix)) {
				resultCandidate = m;
				if (low)
					h = m - 1;
				else
					l = m + 1;
				continue;
			}

			int cmp = e.path.compareTo(prefix);
			if (cmp <= 0) // prefix >= e.path
				l = m + 1;
			else
				h = m - 1;
		}

		return resultCandidate;
	}

	// #################################################
	// ## . . . . . . . Loading Entries . . . . . . . ##
	// #################################################

	private List<ClasspathEntry> loadIndex() {
		List<ClasspathEntry> entries = newList();

		if (!filesystemSources.isEmpty())
			loadFilesystemIndex(entries);
		else
			loadClasspathIndex(entries);

		if (!filesystemSources.isEmpty()) {
			EntriesByArtifact distinctEntries = new EntriesByArtifact();
			for (ClasspathEntry entry : entries)
				distinctEntries.put(entry);
			entries = distinctEntries.entries();
		}
		entries.sort((e1, e2) -> e1.path.compareTo(e2.path));

		return entries;
	}

	private void loadClasspathIndex(List<ClasspathEntry> entries) {
		try {
			Enumeration<URL> resources = classLoader.getResources(RESOURCES_INDEX_FILE_NAME);
			while (resources.hasMoreElements())
				addEntriesFromIndexFile(resources.nextElement(), entries);

			/* A jar needs an explicit index because a ClassLoader cannot enumerate its contents. An IDE, however, exposes project outputs as ordinary
			 * filesystem directories, and there the generated index is absent. Such a directory can be enumerated, so the authored declaration is
			 * expanded instead. A workspace therefore needs no IDE specific builder to materialize the index. */
			loadEntriesFromCpDirs(entries);

		} catch (IOException e) {
			throw new UncheckedIOException("Error while getting Resources: " + RESOURCES_INDEX_FILE_NAME, e);
		}
	}

	private void loadEntriesFromCpDirs(List<ClasspathEntry> entries) throws IOException {
		EntriesByArtifact knownEntries = new EntriesByArtifact();
		for (ClasspathEntry entry : entries)
			knownEntries.addIfAbsent(entry);

		Enumeration<URL> roots = classLoader.getResources("");
		Set<Path> visitedRoots = new LinkedHashSet<>();
		while (roots.hasMoreElements()) {
			URL rootUrl = roots.nextElement();
			if (!"file".equals(rootUrl.getProtocol()))
				continue;

			Path root;
			try {
				root = Path.of(rootUrl.toURI()).toAbsolutePath().normalize();
			} catch (URISyntaxException e) {
				throw new IllegalStateException("Invalid classpath root URL: " + rootUrl, e);
			}
			if (!visitedRoots.add(root) || !Files.isDirectory(root))
				continue;

			// A built root carries the generated index, which the pass above has already read.
			if (Files.isRegularFile(root.resolve(RESOURCES_INDEX_FILE_NAME)))
				continue;

			Path declaration = root.resolve(RESOURCES_DECLARATION_FILE_NAME);
			if (Files.isRegularFile(declaration))
				addEntriesFromDeclarationFile(root, declaration, knownEntries, entries);
		}
	}

	/**
	 * Expands the authored declaration of an artifact. Every listed entry is either a file, which contributes itself, or a folder, which contributes
	 * every file below it.
	 */
	private void addEntriesFromDeclarationFile(Path root, Path declaration, EntriesByArtifact knownEntries, List<ClasspathEntry> entries)
			throws IOException {
		ArtifactName artifact = artifactName(root);

		int lineNum = 0;
		for (String line : Files.readAllLines(declaration, StandardCharsets.UTF_8)) {
			lineNum++;

			line = line.trim();
			if (line.isEmpty() || line.startsWith("#"))
				continue;
			line = canonicalResourcePath(line);

			Path declared = root.resolve(line).normalize();
			if (!declared.startsWith(root)) {
				log.warn("Entry [" + line + "] on line # " + lineNum + " escapes the artifact. Declaration file: " + declaration);
				continue;
			}
			if (!Files.exists(declared)) {
				log.warn("Entry [" + line + "] on line # " + lineNum + " does not exist. Declaration file: " + declaration);
				continue;
			}

			if (Files.isRegularFile(declared)) {
				addDeclaredEntry(root, declared, artifact, knownEntries, entries);
				continue;
			}

			try (var paths = Files.walk(declared)) {
				for (Path resource : paths.filter(Files::isRegularFile).sorted().toList())
					addDeclaredEntry(root, resource, artifact, knownEntries, entries);
			}
		}
	}

	private void addDeclaredEntry(Path root, Path resource, ArtifactName artifact, EntriesByArtifact knownEntries, List<ClasspathEntry> entries)
			throws IOException {
		ClasspathEntry entry = new ClasspathEntry(canonicalResourcePath(root.relativize(resource).toString()), resource.toUri().toURL(),
				artifact.groupId(), artifact.artifactId());

		if (knownEntries.addIfAbsent(entry))
			entries.add(entry);
	}

	/**
	 * Entries by logical path and artifact.
	 * <p>
	 * An unknown groupId belongs to the same artifact as a known one, because one source may know the groupId of an artifact while another does not,
	 * e.g. a jar with its descriptor and a project folder without one. Only two different known groupIds are two artifacts.
	 */
	private static class EntriesByArtifact {
		private final Map<String, List<ClasspathEntry>> byPathAndArtifactId = new LinkedHashMap<>();

		/** Adds the entry unless one of the same artifact and path is there already. */
		boolean addIfAbsent(ClasspathEntry entry) {
			List<ClasspathEntry> sameKey = sameKey(entry);
			for (ClasspathEntry existing : sameKey)
				if (sameArtifact(existing, entry))
					return false;

			sameKey.add(entry);
			return true;
		}

		/** Adds the entry, replacing one of the same artifact and path. A groupId that only the replaced entry knew is kept. */
		void put(ClasspathEntry entry) {
			List<ClasspathEntry> sameKey = sameKey(entry);
			for (int i = 0; i < sameKey.size(); i++) {
				ClasspathEntry existing = sameKey.get(i);
				if (sameArtifact(existing, entry)) {
					sameKey.set(i, entry.groupId.isEmpty() ? new ClasspathEntry(entry.path, entry.url, existing.groupId, entry.artifactId) : entry);
					return;
				}
			}

			sameKey.add(entry);
		}

		List<ClasspathEntry> entries() {
			List<ClasspathEntry> result = new ArrayList<>();
			for (List<ClasspathEntry> sameKey : byPathAndArtifactId.values())
				result.addAll(sameKey);
			return result;
		}

		private List<ClasspathEntry> sameKey(ClasspathEntry entry) {
			return byPathAndArtifactId.computeIfAbsent(entry.path + "\0" + entry.artifactId, k -> new ArrayList<>(1));
		}

		private static boolean sameArtifact(ClasspathEntry one, ClasspathEntry other) {
			return one.groupId.isEmpty() || other.groupId.isEmpty() || one.groupId.equals(other.groupId);
		}
	}

	private static ArtifactName artifactName(Path root) {
		Path descriptor = root.resolve(ARTIFACT_DESCRIPTOR_FILE_NAME);
		if (Files.isRegularFile(descriptor)) {
			ArtifactName described = descriptorArtifactName(descriptor.toUri());
			if (described != null)
				return described;
		}

		return ArtifactName.withoutGroup(derivedArtifactId(root));
	}

	private static String derivedArtifactId(Path root) {
		Path gradleArtifactDirectory = gradleArtifactDirectory(root);
		if (gradleArtifactDirectory != null)
			return gradleArtifactDirectory.getFileName().toString();

		Path artifactDirectory = root.getParent();
		if (artifactDirectory == null)
			return "";

		String outputName = root.getFileName() == null ? "" : root.getFileName().toString();
		if ((outputName.equals("classes") || outputName.equals("test-classes")) && artifactDirectory.getFileName() != null
				&& (artifactDirectory.getFileName().toString().equals("target") || artifactDirectory.getFileName().toString().equals("build")))
			artifactDirectory = artifactDirectory.getParent();

		return artifactDirectory == null || artifactDirectory.getFileName() == null ? "" : artifactDirectory.getFileName().toString();
	}

	/**
	 * Gradle puts the resources of a source set to build/resources/&lt;source set&gt; and its classes to build/classes/&lt;language&gt;/&lt;source set&gt;.
	 * Returns the project directory for such an output folder, or null for any other folder.
	 */
	private static Path gradleArtifactDirectory(Path root) {
		Path parent = root.getParent();
		if (parent == null)
			return null;

		Path buildDirectory = null;
		if (isNamed(parent, "resources"))
			buildDirectory = parent.getParent();
		else if (isNamed(parent.getParent(), "classes"))
			buildDirectory = parent.getParent().getParent();

		if (!isNamed(buildDirectory, "build"))
			return null;

		Path artifactDirectory = buildDirectory.getParent();
		return artifactDirectory == null || artifactDirectory.getFileName() == null ? null : artifactDirectory;
	}

	private static boolean isNamed(Path path, String name) {
		return path != null && path.getFileName() != null && path.getFileName().toString().equals(name);
	}

	private void addEntriesFromIndexFile(URL indexFileUrl, List<ClasspathEntry> entries) {
		String jarUrlPath = artifactPrefix(indexFileUrl);
		if (jarUrlPath == null) {
			log.warn("URL for indexFile does not end with [" + RESOURCES_INDEX_FILE_NAME + "]: " + indexFileUrl);
			return;
		}

		ArtifactName artifact = artifactName(indexFileUrl);

		try (var reader = new BufferedReader(new InputStreamReader(indexFileUrl.openStream(), StandardCharsets.UTF_8))) {
			String line;
			int lineNum = -1;
			while ((line = reader.readLine()) != null) {
				lineNum++;

				line = line.trim();
				if (line.isEmpty() || line.startsWith("#"))
					continue;
				line = canonicalResourcePath(line);

				// From now on we consider line to be a path within given jar / artifact
				Enumeration<URL> files = classLoader.getResources(line);
				if (!files.hasMoreElements()) {
					log.warn("File [" + line + "] referenced on line # " + lineNum + " not found. Index file: " + indexFileUrl);
					continue;
				}

				boolean found = false;
				while (files.hasMoreElements()) {
					URL fileUrl = files.nextElement();
					if (fileUrl.getPath().startsWith(jarUrlPath)) {
						found = true;
						entries.add(new ClasspathEntry(line, fileUrl, artifact.groupId(), artifact.artifactId()));
						break;
					}
				}

				if (!found)
					log.warn("File [" + line + "] referenced on line # " + lineNum + " not found in that same artifact. Index file: " + indexFileUrl);
			}

		} catch (IOException e) {
			throw new UncheckedIOException("Error while reading index file: " + indexFileUrl, e);
		}
	}

	private void loadFilesystemIndex(List<ClasspathEntry> entries) {
		for (FilesystemSource source : filesystemSources)
			loadFilesystemIndex(source, entries);
	}

	private void loadFilesystemIndex(FilesystemSource source, List<ClasspathEntry> entries) {
		if (!Files.isDirectory(source.root))
			throw new IllegalStateException("Classpath resource mirror does not exist: " + source.root);

		if (!source.mappings.isEmpty()) {
			loadFilesystemMappings(source, entries);
			return;
		}

		if (source.directTree) {
			loadFilesystemTree(source, entries);
			return;
		}

		if (!source.indexed) {
			loadFilesystemSlots(source, entries);
			return;
		}

		Path centralIndex = source.root.resolve(FILESYSTEM_INDEX_FILE_NAME);
		if (Files.isRegularFile(centralIndex)) {
			loadCentralFilesystemIndex(source, centralIndex, entries);
			return;
		}

		// Backward compatibility for mirrors produced before the central filesystem index.
		try (var children = Files.list(source.root)) {
			for (Path artifactRoot : children.filter(Files::isDirectory).sorted().toList()) {
				Path index = artifactRoot.resolve(RESOURCES_INDEX_FILE_NAME);
				if (Files.isRegularFile(index))
					addEntriesFromFilesystemIndex(source, artifactRoot, index, entries);
			}
		} catch (IOException e) {
			throw new UncheckedIOException("Error while inspecting classpath resource mirror: " + source.root, e);
		}
	}

	private void loadFilesystemTree(FilesystemSource source, List<ClasspathEntry> entries) {
		try (var paths = Files.walk(source.root)) {
			for (Path resource : paths.filter(Files::isRegularFile).sorted().toList()) {
				String relative = source.root.relativize(resource).toString().replace('\\', '/');
				if (!source.excludes(relative) && !source.excludesExact(relative))
					entries.add(new ClasspathEntry(source.logicalPrefix + relative, resource.toUri().toURL(), source.artifactId));
			}
		} catch (IOException e) {
			throw new UncheckedIOException("Error while inspecting filesystem resource tree: " + source.root, e);
		}
	}

	private void loadFilesystemMappings(FilesystemSource source, List<ClasspathEntry> entries) {
		for (FilesystemMapping mapping : source.mappings) {
			Path resource = source.root.resolve(mapping.materializedPath()).normalize();
			if (!resource.startsWith(source.root.normalize()) || !Files.isRegularFile(resource))
				throw new IllegalStateException("Mapped filesystem resource does not exist: " + resource);
			try {
				entries.add(new ClasspathEntry(mapping.logicalPath(), resource.toUri().toURL(), mapping.groupId(), mapping.artifactId()));
			} catch (IOException e) {
				throw new UncheckedIOException("Cannot address mapped filesystem resource " + resource, e);
			}
		}
	}

	private void loadCentralFilesystemIndex(FilesystemSource source, Path index, List<ClasspathEntry> entries) {
		Properties properties = new Properties();
		try (var in = Files.newInputStream(index)) {
			properties.load(in);
		} catch (IOException e) {
			throw new UncheckedIOException("Error while reading filesystem resource index: " + index, e);
		}

		if (!"1".equals(properties.getProperty("formatVersion")))
			throw new IllegalStateException("Unsupported filesystem resource index format in " + index);

		int artifactCount = requiredInt(properties, "artifact.count", index);
		for (int a = 0; a < artifactCount; a++) {
			String prefix = "artifact." + a + ".";
			String folder = required(properties, prefix + "folder", index);
			// "origin" is the key written before it was renamed to "artifactId"
			String artifactId = properties.getProperty(prefix + "artifactId") != null //
					? required(properties, prefix + "artifactId", index) //
					: required(properties, prefix + "origin", index);
			// optional, a mirror written before the groupId was recorded has none
			String groupId = properties.getProperty(prefix + "groupId", "").trim();
			Path artifactRoot = source.root.resolve(folder).normalize();
			if (!artifactRoot.startsWith(source.root.normalize()) || !Files.isDirectory(artifactRoot))
				throw new IllegalStateException("Invalid filesystem resource slot [" + folder + "] in " + index);

			int resourceCount = requiredInt(properties, prefix + "resource.count", index);
			for (int r = 0; r < resourceCount; r++) {
				String path = required(properties, prefix + "resource." + r + ".path", index).replace('\\', '/');
				if (source.excludes(path))
					continue;

				Path resource = artifactRoot.resolve(path).normalize();
				if (!resource.startsWith(artifactRoot) || !Files.isRegularFile(resource))
					throw new IllegalStateException("Indexed filesystem resource does not exist: " + resource);
				try {
					entries.add(new ClasspathEntry(source.logicalPrefix + path, resource.toUri().toURL(), groupId, artifactId));
				} catch (IOException e) {
					throw new UncheckedIOException("Cannot address filesystem resource " + resource, e);
				}
			}
		}
	}

	private void loadFilesystemSlots(FilesystemSource source, List<ClasspathEntry> entries) {
		try (var children = Files.list(source.root)) {
			for (Path slot : children.filter(Files::isDirectory).sorted().toList()) {
				try (var paths = Files.walk(slot)) {
					for (Path resource : paths.filter(Files::isRegularFile).sorted().toList()) {
						String relative = slot.relativize(resource).toString().replace('\\', '/');
						if (source.excludes(relative))
							continue;
						entries.add(new ClasspathEntry(source.logicalPrefix + relative, resource.toUri().toURL(), slot.getFileName().toString()));
					}
				}
			}
		} catch (IOException e) {
			throw new UncheckedIOException("Error while inspecting filesystem resource slots: " + source.root, e);
		}
	}

	private void addEntriesFromFilesystemIndex(FilesystemSource source, Path artifactRoot, Path index, List<ClasspathEntry> entries) {
		String artifactId = filesystemArtifactId(artifactRoot);
		try (var reader = Files.newBufferedReader(index, StandardCharsets.UTF_8)) {
			String line;
			int lineNum = -1;
			while ((line = reader.readLine()) != null) {
				lineNum++;
				line = line.trim();
				if (line.isEmpty() || line.startsWith("#"))
					continue;
				line = canonicalResourcePath(line);
				if (source.excludes(line))
					continue;

				Path resource = artifactRoot.resolve(line).normalize();
				if (!resource.startsWith(artifactRoot.normalize()) || !Files.isRegularFile(resource)) {
					log.warn("File [" + line + "] referenced on line # " + lineNum + " not found in filesystem artifact mirror: " + index);
					continue;
				}
				entries.add(new ClasspathEntry(source.logicalPrefix + line, resource.toUri().toURL(), artifactId));
			}
		} catch (IOException e) {
			throw new UncheckedIOException("Error while reading filesystem classpath index: " + index, e);
		}
	}

	private static String canonicalResourcePath(String path) {
		return path.replace('\\', '/');
	}

	private String filesystemArtifactId(Path artifactRoot) {
		Path artifactIdFile = artifactRoot.resolve(LEGACY_MIRROR_ARTIFACT_ID_FILE_NAME);
		if (Files.isRegularFile(artifactIdFile)) {
			Properties properties = new Properties();
			try (var in = Files.newInputStream(artifactIdFile)) {
				properties.load(in);
				String artifactId = properties.getProperty("artifactId");
				if (artifactId != null && !artifactId.isBlank())
					return artifactId;
			} catch (IOException e) {
				throw new UncheckedIOException("Error while reading classpath resource artifactId: " + artifactIdFile, e);
			}
		}
		return artifactRoot.getFileName().toString();
	}

	private ArtifactName artifactName(URL indexFileUrl) {
		String value = indexFileUrl.toString();

		// the index URL ends with RESOURCES_INDEX_FILE_NAME, checked by the caller
		String descriptorUri = value.substring(0, value.length() - RESOURCES_INDEX_FILE_NAME.length()) + ARTIFACT_DESCRIPTOR_FILE_NAME;
		try {
			ArtifactName described = descriptorArtifactName(new URI(descriptorUri));
			if (described != null)
				return described;
		} catch (URISyntaxException e) {
			log.warn("Cannot address artifact descriptor next to index file: " + indexFileUrl);
		}

		return ArtifactName.withoutGroup(derivedArtifactId(indexFileUrl));
	}

	/** The artifactId of an artifact without descriptor, derived from the jar name or the project folder of its index file. */
	private String derivedArtifactId(URL indexFileUrl) {
		String value = indexFileUrl.toString();

		int jarEnd = value.indexOf(".jar!/");
		if (jarEnd >= 0) {
			int slash = value.lastIndexOf('/', jarEnd);
			String artifactWithVersion = value.substring(slash + 1, jarEnd);
			int versionSeparator = artifactWithVersion.lastIndexOf('-');
			return versionSeparator > 0 ? artifactWithVersion.substring(0, versionSeparator) : artifactWithVersion;
		}

		/* Eclipse exposes project resources from the configured output directory, e.g. <project>/classes/META-INF/classpath-index.txt. Unlike a jar
		 * URL this URL carries no artifact coordinates, but the project directory is the artifact id by DevRock convention. Maven-style
		 * target/classes and build/classes layouts are handled as well for standalone classpaths. */
		if ("file".equals(indexFileUrl.getProtocol())) {
			try {
				Path index = Path.of(indexFileUrl.toURI());
				Path outputDirectory = index.getParent() == null ? null : index.getParent().getParent();

				Path gradleArtifactDirectory = outputDirectory == null ? null : gradleArtifactDirectory(outputDirectory);
				if (gradleArtifactDirectory != null)
					return gradleArtifactDirectory.getFileName().toString();

				Path artifactDirectory = outputDirectory == null ? null : outputDirectory.getParent();
				if (artifactDirectory != null && ("target".equals(artifactDirectory.getFileName().toString())
						|| "build".equals(artifactDirectory.getFileName().toString())))
					artifactDirectory = artifactDirectory.getParent();

				if (artifactDirectory != null && artifactDirectory.getFileName() != null)
					return artifactDirectory.getFileName().toString();
			} catch (URISyntaxException e) {
				throw new IllegalStateException("Invalid filesystem classpath index URL: " + indexFileUrl, e);
			}
		}
		return "";
	}

	/** The artifact of the given artifact descriptor, or null if the descriptor does not exist or names no artifactId. */
	private static ArtifactName descriptorArtifactName(URI descriptorUri) {
		Properties properties = new Properties();
		try (InputStream in = descriptorUri.toURL().openStream()) {
			properties.load(in);
		} catch (FileNotFoundException | NoSuchFileException e) {
			return null;
		} catch (IOException e) {
			throw new UncheckedIOException("Error while reading artifact descriptor: " + descriptorUri, e);
		}

		String artifactId = properties.getProperty("artifactId");
		if (artifactId == null || artifactId.isBlank())
			return null;

		return new ArtifactName(properties.getProperty("groupId", "").trim(), artifactId.trim());
	}

	/** The identity of the artifact a resource belongs to. Either part is an empty string if it is not known. */
	private record ArtifactName(String groupId, String artifactId) {
		static ArtifactName withoutGroup(String artifactId) {
			return new ArtifactName("", artifactId);
		}
	}

	private String artifactPrefix(URL indexFileUrl) {
		String path = indexFileUrl.getPath();
		if (!path.endsWith(RESOURCES_INDEX_FILE_NAME))
			return null;
		return path.substring(0, path.length() - RESOURCES_INDEX_FILE_NAME.length());
	}

	private static Path requireFilesystemRoot(Path path) {
		if (path == null)
			throw new NullPointerException("filesystemRoot must not be null");
		return path;
	}

	private static List<FilesystemSource> requireFilesystemSources(List<FilesystemSource> sources) {
		if (sources == null)
			throw new NullPointerException("filesystemSources must not be null");
		if (sources.isEmpty())
			throw new IllegalArgumentException("At least one filesystem source is required");
		List<FilesystemSource> copy = List.copyOf(sources);
		if (copy.stream().anyMatch(java.util.Objects::isNull))
			throw new NullPointerException("filesystemSources must not contain null");
		return copy;
	}

	private static Set<String> normalizeResourcePrefixes(Collection<String> prefixes) {
		if (prefixes == null)
			throw new NullPointerException("excludedResourcePrefixes must not be null");
		Set<String> result = new LinkedHashSet<>();
		for (String prefix : prefixes)
			result.add(normalizeLogicalPrefix(prefix));
		return Set.copyOf(result);
	}

	private static Set<String> normalizeResourcePaths(Collection<String> paths) {
		if (paths == null)
			throw new NullPointerException("excludedRelativePaths must not be null");
		Set<String> result = new LinkedHashSet<>();
		for (String path : paths) {
			String normalized = canonicalResourcePath(requireMappingValue(path, "excludedRelativePath"));
			Path parsed = Path.of(normalized).normalize();
			String canonical = canonicalResourcePath(parsed.toString());
			if (parsed.isAbsolute() || canonical.equals("..") || canonical.startsWith("../"))
				throw new IllegalArgumentException("Invalid excluded relative path: " + path);
			result.add(canonical);
		}
		return Set.copyOf(result);
	}

	private static String requireMappingValue(String value, String name) {
		if (value == null || value.isBlank())
			throw new IllegalArgumentException(name + " must not be empty");
		String normalized = canonicalResourcePath(value);
		Path parsed = Path.of(normalized).normalize();
		String canonical = canonicalResourcePath(parsed.toString());
		if (parsed.isAbsolute() || canonical.equals("..") || canonical.startsWith("../"))
			throw new IllegalArgumentException("Invalid " + name + ": " + value);
		return canonical;
	}

	private static String required(Properties properties, String name, Path source) {
		String value = properties.getProperty(name);
		if (value == null || value.isBlank())
			throw new IllegalStateException("Missing property [" + name + "] in filesystem resource index " + source);
		return value;
	}

	private static int requiredInt(Properties properties, String name, Path source) {
		String value = required(properties, name, source);
		try {
			int result = Integer.parseInt(value);
			if (result < 0)
				throw new NumberFormatException("negative");
			return result;
		} catch (NumberFormatException e) {
			throw new IllegalStateException("Invalid non-negative integer property [" + name + "] in " + source + ": " + value, e);
		}
	}

	private static String normalizeLogicalPrefix(String prefix) {
		if (prefix == null)
			throw new NullPointerException("logicalPrefix must not be null");
		String normalized = prefix.replace('\\', '/');
		while (normalized.startsWith("/"))
			normalized = normalized.substring(1);
		if (!normalized.isEmpty() && !normalized.endsWith("/"))
			normalized += "/";
		String path = normalized.isEmpty() ? normalized : normalized.substring(0, normalized.length() - 1);
		if (!path.isEmpty())
			for (String element : path.split("/", -1))
				if (element.equals(".") || element.equals("..") || element.isEmpty())
					throw new IllegalArgumentException("Invalid logical prefix: " + prefix);
		return normalized;
	}

	public static final class FilesystemSource {
		private final Path root;
		private final String logicalPrefix;
		private final Set<String> excludedResourcePrefixes;
		private final Set<String> excludedResourcePaths;
		private final boolean indexed;
		private final boolean directTree;
		private final String artifactId;
		private final List<FilesystemMapping> mappings;

		private FilesystemSource(Path root, String logicalPrefix, Set<String> excludedResourcePrefixes,
				Set<String> excludedResourcePaths, boolean indexed, boolean directTree, String artifactId,
				List<FilesystemMapping> mappings) {
			this.root = root;
			this.logicalPrefix = logicalPrefix;
			this.excludedResourcePrefixes = excludedResourcePrefixes;
			this.excludedResourcePaths = excludedResourcePaths;
			this.indexed = indexed;
			this.directTree = directTree;
			this.artifactId = artifactId;
			this.mappings = mappings;
		}

		public Path root() {
			return root;
		}

		public String logicalPrefix() {
			return logicalPrefix;
		}

		private boolean excludes(String path) {
			String normalized = path.replace('\\', '/');
			return excludedResourcePrefixes.stream().anyMatch(normalized::startsWith);
		}

		private boolean excludesExact(String path) {
			return excludedResourcePaths.contains(path.replace('\\', '/'));
		}
	}
}
